spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 424629007631-55vci0bsgdt2vbo73mrc7537d18dvsde.apps.googleusercontent.com
            client-secret: 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
            redirectUri: http://${api_gateway_url}:8080/login/oauth2/code/google
            scope:
              - profile
          twitter:
            client-id: M2RKdWFoTUw4X3k2aldOWU5JLXU6MTpjaQ
            client-secret: jgmFmKBMj5RYPcdTwKLPWT_Liw2hsBy6Q1qrpF_wdbhQHiN4un
            scope:
              - read:user
            redirect-uri: http://localhost/login/oauth2/code/twitter
            authorization-grant-type: authorization_code
            client-authentication-method: post
        provider:
          twitter:
            authorization-uri: https://api.twitter.com/oauth/authorize
            token-uri: https://api.twitter.com/oauth/access_token
            user-info-uri: https://api.twitter.com/1.1/account/verify_credentials.json
            user-name-attribute: screen_name

api_gateway_url: localhost


custom:
  react:
    redirect_uri: http://localhost:3000/loginSuccess # 기본값 설정
  springboot:
    user_service_url: http://localhost:8081
