api_gateway_url: mygemini.co.kr

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${api_gateway_url}:3306/gemini_user?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=true
    username: gemini
    password: starrail1@
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 10
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
      data-source-properties:
        rewriteBatchedStatements: true
