spring:
  profiles:
    active: prod # 기본으로 쓸 프로파일

  application:
    name: user-service

  http:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 50MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        default_batch_fetch_size: ${chunkSize:100}
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
        format_sql: true

  redis:
    host: mygemini.co.kr
    port: 6379
    password: b106b106

  data:
    mongodb:
      host: mygemini.co.kr
      port: 27017
      database: gemini
      username: gemini12
      password: starrail12
      authentication-database: admin


server:
  port: 8081

sd:
  url: http://13.124.20.123/ml_api
